fileid_herotest_sprite_bank             equ 0
fileid_herotest_palette                 equ 1
fileid_herotest_sprite                  equ 2
fileid_herotest_big_sprite_bank         equ 3
fileid_herotest_big_palette             equ 4
fileid_herotest_big_sprite              equ 5
fileid_testsprite_sprite_bank           equ 6
fileid_testsprite_palette               equ 7
fileid_testsprite_sprite                equ 8
fileid_testsprite2_sprite_bank          equ 9
fileid_testsprite2_palette              equ 10
fileid_testsprite2_sprite               equ 11
fileid_testtiles_bank                   equ 12
fileid_testtiles_map                    equ 13
fileid_testtiles_palette                equ 14
fileid_untitled_splash_bank             equ 15
fileid_untitled_splash_map              equ 16
fileid_untitled_splash_palette          equ 17
fileid_herotestpng_sprite_bank          equ 18
fileid_herotestpng_palette              equ 19
fileid_herotestpng_sprite               equ 20
fileid_housetiles_bank                  equ 21
fileid_housetiles_map                   equ 22
fileid_housetiles_palette               equ 23
fileid_signpost_bank                    equ 24
fileid_signpost_map                     equ 25
fileid_signpost_palette                 equ 26
fileid_testmap_map                      equ 27
fileid_testmap2_map                     equ 28